### ISSUE TITLE
Fix rotate when use labelsFilter

### ISSUE THREAD

**Issue by Huxpro** [leighquince/Chart.js#13]
the rotation of labels is calculated with all label length, 
can you make the rotation depends on the label length after filter?

**Comment by leighquince** [comment]
hey sorry for the late reply. I had tried this when i was first developing the filter and when there is a lot of data I found that without rotation the label covered several datapoints (in all of my use cases for creating it the reason a filter is there is because they can't all fit in so most of the time there is a lot of data on the graph). With this overlap it became hard to distinguish the original datapoint the label was trying to show. With the rotation this is obvious because the label ends at the point where the data is on the graph. Because of that i decided against re adjusting the rotation after the filter was applied.
