### ISSUE TITLE
is it possible to hide the dot if the value is same as previous 

### ISSUE THREAD

**Issue by dmsherazi** [leighquince/Chart.js#21]
I am using a chart in my page using chart.js I have on my x axis dates while on my y axis values(cost). I want to keep the line chart continue its value until there is a change and have coded for that. Here is the output

[http://i.stack.imgur.com/nWfrR.png](url)

In this as marked if the value is same I have dots plotted. I have an option to remove all dots but I want to remove dots if the value is same as previous.(there is no change). I would like to know if this is doable. If please guide me how to go for it?

**Comment by leighquince** [comment]
hey yeah you can do this by updating the draw method of the line chart (or adding a creating a new chart type and overriding the draw method)  you could do something that would mark a `point` so that if it is the same as the previous point you flag it to not draw the dot. so something like

added around line 394 inside the loop of the dataset points:

```
if(index > 0 && (dataset.points[index - 1].value === point.value))
                    {
                        point.skipPoint = true;
                    }
```

then around line 455 (where it draws the points) update the if statement to check for this flag

```
if (!point.ignore && !point.skipPoint)
                        point.draw();
```
