### ISSUE TITLE
positionning stacked bars

### ISSUE THREAD

**Issue by adneneBen** [leighquince/Chart.js#3]
hello 
i would like to ask if is it possible to draw stacked bars not from the graph base but from the end of the previous bar like image below
![capture d ecran 2015-02-02 a 10 25 14](https://cloud.githubusercontent.com/assets/10808071/6003907/840b3d0c-aaff-11e4-9276-c08929e78fc9.png)
thanks in advance

**Comment by leighquince** [comment]
Hi i have changed the option name for the overlaying bars feature to `overlayBars` (https://github.com/leighquince/Chart.js/commit/54896333c6126fca043249ed388d5c1af9aca8e4)  now to avoid the misleading title of stacked and what it was previously doing. This feature can now be called stacked( or something like) that but going to have a think about the best way to do it as it might make sense to have this as a new chart rather than an option.

**Comment by leighquince** [comment]
i've realized there is actually a community extension that does this - https://github.com/Regaddi/Chart.StackedBar.js
